name: Windows Build Test

on: [push]

jobs:
  build:
    name: Windows Build
    runs-on: windows-latest
    steps:
        uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        id: qt_install
      - name: Run QMake
        run: qmake ci_test.pro
      - name: Build
        run: nmake
      - name: Test
        run: release/ci_test.exe --test
