name: Build Test

on: [push]

jobs:
  build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Setup
        uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Run QMake
        run: qmake ci_test.pro
      - name: Build
        run: nmake debug
      - name: Deploy
        run: windeployqt.exe debug
      - name: Test
        run: debug/ci_test.exe --test
