name: Build Test

on: [push, pull_request]

jobs:
  windows:
    name: Windows Build and Test
    runs-on: windows-latest
    steps:
      - name: MSVC Environment Setup
        uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Run QMake
        run: qmake ci_test.pro
      - name: Build
        run: nmake debug
      - name: Deploy
        run: windeployqt.exe debug
      - name: Test
        run: cmd.exe /C "start /wait debug/ci_test.exe --test & exit /b errorlevel"
  linux:
    name: Linux Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Run QMake
        run: qmake "CONFIG+=debug" ci_test.pro
      - name: Build
        run: make
      - name: Directory Setup
        run: mkdir -p temp_ci
      - name: Test
        run: cd temp_ci && ../ci_test --test
        env:
          LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${Qt5_Dir}/bin:${Qt5_Dir}/plugins
