name: Build Test

on: [push, pull_request]

jobs:
  windows:
    name: Windows Build and Test
    runs-on: windows-latest
    steps:
      - name: MSVC Environment Setup
        uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Run QMake
        run: qmake ci_test.pro
      - name: Build
        run: nmake debug
      - name: Deploy
        run: windeployqt.exe debug
      - name: Test
        run: pwsh.EXE -Command "exit (Start-Process -FilePath 'debug/ci_test.exe' -argumentlist '--test' -wait -Passthru).ExitCode"
