name: Build Test

on: [push, pull_request]

jobs:
  windows:
    name: Windows Test
    runs-on: windows-latest
    steps:
      - name: MSVC Environment Setup
        uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Run QMake
        run: qmake ci_test.pro
      - name: Build
        run: nmake debug
      - name: Deploy
        run: windeployqt.exe debug
      - name: Test
        run: cmd.exe /C "start /wait debug/ci_test.exe --test & exit /b errorlevel"
  linux:
    name: Linux (Build only)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Run QMake
        run: qmake ci_test.pro
      - name: Build
        run: make
  mac:
    name: Mac (Build only)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Run QMake
        run: qmake ci_test.pro
      - name: Build
        run: make
